"""Stable public contract for the Presentation module."""

from ..application.service import (
    PresentationError,
    PresentationPresetUnknown,
    PresentationRevisionNotFound,
    apply_admin_preset,
    get_admin_presentation,
    public_presentation,
    rollback_admin_presentation,
    save_admin_presentation,
    toggle_admin_presentation,
)
from ..domain.config import (
    HOME_BLOCK_TYPES,
    PRESET_IDS,
    PRESETS,
    SOFTWARE_PRESET,
    TUTORIAL_PRESET,
    HomeBlock,
    NavigationItem,
    PresentationConfig,
    ThemeTokens,
    config_dict,
    config_to_json,
    default_presentation,
    ordered_blocks,
    validate_config,
)

__all__ = [
    "HOME_BLOCK_TYPES",
    "PRESET_IDS",
    "PRESETS",
    "SOFTWARE_PRESET",
    "TUTORIAL_PRESET",
    "ThemeTokens",
    "NavigationItem",
    "HomeBlock",
    "PresentationConfig",
    "config_dict",
    "config_to_json",
    "default_presentation",
    "ordered_blocks",
    "validate_config",
    "PresentationError",
    "PresentationPresetUnknown",
    "PresentationRevisionNotFound",
    "get_admin_presentation",
    "save_admin_presentation",
    "apply_admin_preset",
    "rollback_admin_presentation",
    "toggle_admin_presentation",
    "public_presentation",
]
