"""Catalog C1 application layer: create, edit, bind, preview, publish.

Backward-compatible shim. The implementation has been split (C2) into:
- modules/catalog/application/catalog_entry.py   (entry + shared primitives)
- modules/catalog/application/catalog_release.py (release/asset/location)

This module re-exports every public symbol so existing imports
``from cloudsite.services.catalog import X`` and ``from ..services import catalog``
continue to work unchanged. No business logic lives here.
"""
from __future__ import annotations

from ..modules.catalog.application.catalog_entry import (
    ASSET_ID_PREFIX,
    DEFAULT_RELEASE_SLUG,
    DEFAULT_RELEASE_TITLE,
    ENTRY_ID_PREFIX,
    LOCATION_ID_PREFIX,
    RELEASE_ID_PREFIX,
    _ID_HEX_LEN,
    _UNSET,
    CatalogAssetNotDownloadable,
    CatalogEntryNotFound,
    CatalogError,
    CatalogPublishValidationFailed,
    CatalogRevisionConflict,
    CatalogSlugConflict,
    CreateCatalogEntryResult,
    LocationResolution,
    PreviewValidationResult,
    PublishCatalogEntryResult,
    _collect_location_blockers,
    _entry_snapshot,
    _new_id,
    _resolve_location,
    count_catalog_entries,
    create_catalog_entry,
    enabled_root_ids,
    get_catalog_entry,
    list_catalog_entries,
    publish_catalog_entry,
    update_catalog_entry,
    validate_catalog_entry_for_preview,
)
from ..modules.catalog.application.catalog_release import (
    AssetDownloadTarget,
    AttachCatalogLocationResult,
    CatalogAssetNotFound,
    CatalogLocationInvalid,
    CatalogReleaseNotFound,
    CreateCatalogAssetResult,
    CreateCatalogReleaseResult,
    _asset_snapshot,
    _clear_other_recommendations,
    _entry_content_type_for_asset,
    _release_snapshot,
    attach_catalog_location,
    create_catalog_asset,
    create_catalog_release,
    delete_catalog_location,
    get_catalog_asset,
    get_catalog_release,
    list_catalog_assets,
    list_catalog_locations,
    list_catalog_releases,
    resolve_asset_download_target,
    update_catalog_asset,
    update_catalog_location,
    update_catalog_release,
)

__all__ = [
    # constants
    "ENTRY_ID_PREFIX",
    "RELEASE_ID_PREFIX",
    "ASSET_ID_PREFIX",
    "LOCATION_ID_PREFIX",
    "_ID_HEX_LEN",
    "DEFAULT_RELEASE_SLUG",
    "DEFAULT_RELEASE_TITLE",
    "_UNSET",
    # exceptions
    "CatalogError",
    "CatalogEntryNotFound",
    "CatalogReleaseNotFound",
    "CatalogAssetNotFound",
    "CatalogRevisionConflict",
    "CatalogSlugConflict",
    "CatalogLocationInvalid",
    "CatalogPublishValidationFailed",
    "CatalogAssetNotDownloadable",
    # dataclasses
    "CreateCatalogEntryResult",
    "CreateCatalogReleaseResult",
    "CreateCatalogAssetResult",
    "LocationResolution",
    "AttachCatalogLocationResult",
    "PreviewValidationResult",
    "PublishCatalogEntryResult",
    "AssetDownloadTarget",
    # entry functions
    "_new_id",
    "_entry_snapshot",
    "enabled_root_ids",
    "_resolve_location",
    "count_catalog_entries",
    "create_catalog_entry",
    "get_catalog_entry",
    "list_catalog_entries",
    "update_catalog_entry",
    "_collect_location_blockers",
    "validate_catalog_entry_for_preview",
    "publish_catalog_entry",
    # release/asset/location functions
    "_clear_other_recommendations",
    "create_catalog_release",
    "create_catalog_asset",
    "_entry_content_type_for_asset",
    "attach_catalog_location",
    "_release_snapshot",
    "_asset_snapshot",
    "get_catalog_release",
    "get_catalog_asset",
    "list_catalog_releases",
    "list_catalog_assets",
    "list_catalog_locations",
    "update_catalog_release",
    "update_catalog_asset",
    "update_catalog_location",
    "delete_catalog_location",
    "resolve_asset_download_target",
]
